name: 'Workplace Release Notes'
description: 'Issue Workplace Release Notes post to a group'
inputs:
  github_token:
    description: A Github token for the repo, usually `{{ github.token }}`.
    required: true
  repo_name:
    description: The repo name that we're working on.
    required: true
  product_name:
    description: The optional different name for the product to appear in posts
    required: false
  facebook_token:
    description: The facebook posting token
    required: true
  facebook_groupid:
    description: The group to post to 
    required: true
runs:
  using: 'node12'
  main: 'index.js'
